#!/usr/bin/python3
from random import choices
from random import randint 


symbols = "abcdefghijklmnopqrstuvwxyz "
def get_string(str_len):
    return ''.join(choices(symbols, k=str_len))

with open('tests/1', 'w') as out:
    out.write('{}\n'.format(get_string(10)))

for i in range(7):
    with open('tests/{}'.format(i + 2), 'w') as out:
        out.write('{}\n'.format(get_string(randint(1, 10**6))))

with open('tests/9', 'w') as out:
    out.write('{}\n'.format(get_string(0)))

with open('tests/10', 'w') as out:
    out.write('{}\n'.format(get_string(10**6)))
