#!/usr/bin/python3
from random import randint

with open('tests/1', 'w') as out:
    out.write('{} {}\n'.format(randint(-10, 10), randint(-10, 10)))

with open('tests/2', 'w') as out:
    out.write('{} {}\n'.format(randint(-10, 10), randint(-10, 10)))

for i in range(18):
    with open('tests/{}'.format(i + 3), 'w') as out:
        out.write('{} {}\n'.format(randint(-(10**9), 10**9), randint(-(10**9), 10**9)))
