#!/usr/bin/python3
import random as r

max_value = 10**9

def gen_first_test():
    f = open('tests/1', 'w')
    f.write('2\n10 2\n')

def gen_second_test():
    f = open('tests/2', 'w')
    f.write('1\n5\n')

def gen_rand_test(test_num, n, ans):
    f = open('tests/{}'.format(test_num), 'w') 
    f.write('{}\n'.format(n));
    for i in range(n):
        f.write('{} '.format(ans * r.randint(1, max_value // ans)))

gen_first_test()
gen_second_test()

for num in range(3, 11):
    if r.randint(1, 7) == 1:
        gen_rand_test(num, 1000, 1)
    else:
        gen_rand_test(num, 1000, r.randint(1, max_value))

for num in range(11, 20):
    if r.randint(1, 7) == 1:
        gen_rand_test(num, 10**6, 1)
    else:
        gen_rand_test(num, 10**6, r.randint(1, max_value))

gen_rand_test(20, 10**6, max_value)
