#!/bin/bash

#################################################
#
# Command line control script.
# Use it to control Judex system.
# It requires root privileges.
#
#################################################

function error {
    echo "Error. $1"
    exit 1
}

[[ "$EUID" != "0" ]] && error "Root privileges required"

source <(grep src= "/etc/judex/judex.conf")

function _start {
    echo "Start"
    echo "Args: $@"
    a2ensite judex.tech.conf
    if ! systemctl is-active --quiet apache2; then
      systemctl start apache2
    else
      systemctl restart apache2
    fi
    if ! systemctl is-active --quiet mysql; then
      systemctl start mysql
    fi
    phpenmod mysqli
    src/Testing/loadbalancerctl.py start
}

function _stop {
    echo "Stop"
    echo "Args: $@"
    src/Testing/loadbalancerctl.pu stop
}

function _restart {
    echo "Restart"
    echo "Args: $@"
}

args=()
while [[ "$#" -ge "1" ]]; do
    [[ "$1" == -* ]] && break
    args+=( "$1" )
    shift
done

if [[ "${#args[@]}" -gt "0" ]]; then
    arg="${args[0]}"
    args=("${args[@]:1}")
    case "$arg" in
    start)
        _start "${args[@]}"
    ;;
    stop)
        _stop "${args[@]}"
    ;;
    restart)
        _restart "${args[@]}"
    ;;
    *)
        error "Invalid option $arg."
   esac
   unset arg
fi
